name: suma

on: push

jobs:
  suma:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Sec
        uses: advanced-security/python-lint-code-scanning-action@v1
      
